#!/usr/bin/env bash
# worktree-isolation installer.
#
# Usage (from inside a git repo):
#   curl -sSL https://raw.githubusercontent.com/rzykie/worktree-isolation/v0.1.0/install.sh \
#     | bash -s -- \
#         --repo myapp \
#         --worktrees-root "$HOME/.claude/worktrees/myapp" \
#         --registry "$HOME/.myapp-worktrees.json" \
#         --db-prefix myapp_ \
#         [--template-db myapp_dev] \
#         [--base-branch develop] \
#         [--bootstrap .claude/hooks/bootstrap.sh] \
#         [--target /path/to/repo]   # default: pwd
#
# Drops files into <target>/.claude/hooks/ and writes worktree-isolation.conf
# from the supplied flags. Idempotent — re-running upgrades the lib but
# preserves your conf and bootstrap.sh.

set -euo pipefail

REF="${WORKTREE_ISOLATION_REF:-v0.1.0}"
REPO_SLUG="rzykie/worktree-isolation"

REPO_NAME=""
WORKTREES_ROOT=""
REGISTRY_PATH=""
DB_PREFIX=""
TEMPLATE_DB=""
BASE_BRANCH=""
BOOTSTRAP_HOOK=""
TARGET="$(pwd)"

usage() {
    sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'
    exit "${1:-0}"
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --repo)            REPO_NAME="$2"; shift 2 ;;
        --worktrees-root)  WORKTREES_ROOT="$2"; shift 2 ;;
        --registry)        REGISTRY_PATH="$2"; shift 2 ;;
        --db-prefix)       DB_PREFIX="$2"; shift 2 ;;
        --template-db)     TEMPLATE_DB="$2"; shift 2 ;;
        --base-branch)     BASE_BRANCH="$2"; shift 2 ;;
        --bootstrap)       BOOTSTRAP_HOOK="$2"; shift 2 ;;
        --target)          TARGET="$2"; shift 2 ;;
        --ref)             REF="$2"; shift 2 ;;
        -h|--help)         usage 0 ;;
        *) echo "unknown flag: $1" >&2; usage 1 ;;
    esac
done

err() { echo "install.sh: $*" >&2; exit 1; }

[[ -z "$REPO_NAME" ]]       && err "--repo is required"
[[ -z "$WORKTREES_ROOT" ]]  && err "--worktrees-root is required"
[[ -z "$REGISTRY_PATH" ]]   && err "--registry is required"
[[ -z "$DB_PREFIX" ]]       && err "--db-prefix is required"
[[ ! -d "$TARGET" ]]        && err "target directory does not exist: $TARGET"

for cmd in curl tar python3; do
    command -v "$cmd" >/dev/null 2>&1 || err "required command not found: $cmd"
done

HOOKS_DIR="$TARGET/.claude/hooks"
mkdir -p "$HOOKS_DIR/lib"

TARBALL_URL="https://codeload.github.com/${REPO_SLUG}/tar.gz/refs/tags/${REF}"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

echo "→ downloading worktree-isolation@${REF}"
if ! curl -fsSL "$TARBALL_URL" | tar -xz -C "$TMPDIR"; then
    # tag may not exist yet; fall back to a branch ref
    BRANCH_URL="https://codeload.github.com/${REPO_SLUG}/tar.gz/refs/heads/${REF}"
    echo "  tag not found; trying branch '${REF}'"
    curl -fsSL "$BRANCH_URL" | tar -xz -C "$TMPDIR" \
        || err "could not download ${REF} from ${REPO_SLUG}"
fi

SRC="$(find "$TMPDIR" -maxdepth 1 -type d -name 'worktree-isolation-*' | head -n1)"
[[ -z "$SRC" ]] && err "extracted archive did not contain expected directory"

echo "→ installing hooks into $HOOKS_DIR"
install -m 0755 "$SRC/hooks/worktree-create.sh" "$HOOKS_DIR/worktree-create.sh"
install -m 0755 "$SRC/hooks/worktree-remove.sh" "$HOOKS_DIR/worktree-remove.sh"
install -m 0644 "$SRC/hooks/lib/worktree-common.sh" "$HOOKS_DIR/lib/worktree-common.sh"
install -m 0755 "$SRC/hooks/lib/registry.py" "$HOOKS_DIR/lib/registry.py"

if [[ -e "$HOOKS_DIR/bootstrap.sh.example" ]]; then
    echo "  keeping existing bootstrap.sh.example"
else
    install -m 0644 "$SRC/hooks/bootstrap.sh.example" "$HOOKS_DIR/bootstrap.sh.example"
fi

CONF="$HOOKS_DIR/worktree-isolation.conf"
if [[ -e "$CONF" ]]; then
    echo "  keeping existing $CONF (delete and re-run to regenerate)"
else
    echo "→ writing $CONF"
    {
        echo "# Generated by worktree-isolation install.sh @ ${REF}"
        echo "REPO_NAME=$REPO_NAME"
        echo "WORKTREES_ROOT=$WORKTREES_ROOT"
        echo "REGISTRY_PATH=$REGISTRY_PATH"
        echo "DB_PREFIX=$DB_PREFIX"
        [[ -n "$TEMPLATE_DB" ]]    && echo "TEMPLATE_DB=$TEMPLATE_DB"
        [[ -n "$BASE_BRANCH" ]]    && echo "BASE_BRANCH=$BASE_BRANCH"
        [[ -n "$BOOTSTRAP_HOOK" ]] && echo "BOOTSTRAP_HOOK=$BOOTSTRAP_HOOK"
    } > "$CONF"
    chmod 0644 "$CONF"
fi

cat <<EOF

✓ installed worktree-isolation@${REF} into $HOOKS_DIR

next steps:
  1. (optional) cp .claude/hooks/bootstrap.sh.example .claude/hooks/bootstrap.sh
     edit it to run your project's setup (uv sync, npm install, migrations)
     chmod +x .claude/hooks/bootstrap.sh
  2. wire the hooks into Claude Code's worktree settings (.claude/settings.json):
       "hooks": {
         "WorktreeCreate": [{"hooks": [{"type": "command",
            "command": ".claude/hooks/worktree-create.sh"}]}],
         "WorktreeRemove": [{"hooks": [{"type": "command",
            "command": ".claude/hooks/worktree-remove.sh"}]}]
       }
  3. test it by creating a new worktree from Claude Code.

inspect the registry any time:
  python3 .claude/hooks/lib/registry.py inspect
manually evict stale entries:
  python3 .claude/hooks/lib/registry.py sweep
EOF
